### ISSUE TITLE
📝 Documentation: Wrong .NET version?

### ISSUE THREAD

**Issue by onkobu** [Kryptor-Software/Kryptor#33]
### Description
[Installation](https://www.kryptor.co.uk/installation) suggests to install and links to .NET 5 whereas global.json requires 6.100.

**Comment by samuel-lucas6** [comment]
Hi @onkobu,

Good spot! However, that's currently correct because the latest release uses .NET 5. The master branch is in development and not ready to be used. At the moment, it's just refactoring stuff, but for the release of v4, there will be lots of breaking changes and building from the master branch would lead to things potentially not working and incompatibility. Therefore, please use the latest release source code, as explained [here](https://www.kryptor.co.uk/installation#downloading-the-source-code). Hope that helps.

**Comment by onkobu** [comment]
That was fast. Didn't check whether master == last release. Then it is absolutely fine. Docs also clearly state to use the release archives.
